# Generated by Django 4.2.11 on 2025-01-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_person_personfilmwork_person_persons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники Кинопроизведения'},
        ),
    ]
