# Generated by Django 4.2.11 on 2025-01-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='certificate',
            field=models.TextField(blank=True, verbose_name='certificate'),
        ),
    ]
