# Generated by Django 4.2.11 on 2025-01-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_filmwork_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='test',
        ),
    ]
