# Generated by Django 4.2.11 on 2025-01-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_name_genre_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='test',
            new_name='name',
        ),
    ]
