# Generated by Django 4.2.11 on 2025-01-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_filmwork_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
