# Generated by Django 4.2.11 on 2025-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('Фильм', 'Movie'), ('tv show', 'Tv Show'), ('serial', 'Serial')], default='Фильм', max_length=10),
        ),
    ]
