# Generated by Django 4.2.11 on 2025-01-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_filmwork_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Участника', 'verbose_name_plural': 'Участники Кинопроизведения'},
        ),
    ]
