# Generated by Django 4.2.11 on 2025-01-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_person_options'),
    ]

    operations = [
    ]
