# Generated by Django 4.2.11 on 2025-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('tv_show', 'Шоу'), ('soap_opera', 'Сериал'), ('cartoon', 'Мультфильм')], default='movie', max_length=10, verbose_name='type'),
        ),
    ]
