# Generated by Django 4.2.11 on 2025-01-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_alter_filmwork_created_alter_filmwork_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
