# Generated by Django 4.2.11 on 2025-01-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_test_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('фильм', 'Movie'), ('тв шоу', 'Tv Show'), ('сериал', 'Serial')], default='фильм', max_length=10),
        ),
    ]
