# Generated by Django 4.2.11 on 2025-01-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_filmwork_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv show', 'Tv Show'), ('seerial', 'Serial')], default='movie', max_length=10),
        ),
    ]
