# Generated by Django 4.2.11 on 2025-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_filmwork_type_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(verbose_name='дата создания'),
        ),
    ]
