# Generated by Django 4.2.5 on 2024-02-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_add_certificate_and_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="certificate",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="certificate"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="movies/", verbose_name="file"
            ),
        ),
    ]
