# Generated by Django 4.2.5 on 2024-02-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_change_fields_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="certificate",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="certificate"
            ),
        ),
    ]
