# Generated by Django 4.2.5 on 2024-02-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_null_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
