# Generated by Django 4.2.5 on 2024-02-09 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_null_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmwork",
            name="certificate",
        ),
    ]
